name: Simple Docker CI/CD

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify files
        run: |
          [ -f "kursach.py" ] || exit 1
          [ -f "requirements.txt" ] || exit 1
          [ -f "Dockerfile" ] || exit 1

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-files
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify Flask installation
        run: |
          python -c "import flask; print('Flask is installed correctly')"
      - name: Verify Flask version
        run: |
          pip show flask
      - name: Run simple test
        run: |
          python -c "from kursach import app; print('App imported successfully')"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kursach:latest
            ${{ secrets.DOCKER_USERNAME }}/kursach:${{ github.sha }}
